version: '3.8'

services:
  database:
    image: mongo:4.4.8
    container_name: budgetpals_database
    ports:
      - 27017:27017
    volumes:
      - database_volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DB_NAME
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USR
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PSW

  api:
    build:
      context: api
      dockerfile: docker/Dockerfile.local
    container_name: budgetpals_api
    environment:
      - API_PORT=$API_PORT
      - API_URL=$API_URL
      - NODE_ENV=$NODE_ENV
      - DATABASE_HOST=database
      - DATABASE_USER=$MONGO_ROOT_USR
      - DATABASE_PASSWORD=$MONGO_ROOT_PSW
      - DATABASE_NAME=$MONGO_DB_NAME
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
    ports:
      - 9229:9229
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - database

  nginx:
    image: nginx:1.20-alpine
    container_name: budgetpals_nginx
    ports:
      - 3333:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  database_volume:
