# Dockerfile for development environment
FROM node:20.7.0-alpine3.18

WORKDIR /app

# Install bcypt dependencies
RUN apk add --no-cache python3 make gcc g++

COPY package.json .
COPY package-lock.json .

RUN npm ci
RUN npm rebuild bcrypt --build-from-source

COPY . .

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
