name: Node.js CI

on: [push]

jobs:
  unit-tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.1.0'
      - run: | 
          cd api
          npm ci
          npm run test

  integration-tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.1.0'
      - run: | 
          cd api
          npm ci
          npm run test:integration

  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: create env file
      run: |
        touch .env
        echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> .env
        echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> .env
        echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
        echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
        echo JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} >> .env

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.3.1
      with:
        deliverables: api/app.yaml
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}